---
- name: Provision docker-compose to hosts
  hosts: all
  vars:
    use_rds: "false"
  roles:
    - { role: externaldatabase, when: use_rds == "true" }
    - docker
    - docker-compose
    - docker-redmine
    - iptables


        
        





  
  
  


