---
# tasks file for redmine-docker
- name: Create the user redmine-docker and add it to the docker group
  become: yes
  user:
    name: docker-redmine
    shell: /bin/bash
    groups: docker
    append: yes

- name: Create docker-redmine production directory
  become: yes
  file:
    path: /home/docker-redmine/redmine-prd
    state: directory
    owner: docker-redmine
    group: docker-redmine
    mode: '0755'

- name: Copy docker-compose yml
  become: yes
  template:
    src: docker-compose.yml.j2
    dest: '/home/docker-redmine/redmine-prd/docker-compose.yml'
    owner: docker-redmine
    group: docker-redmine

- name: Docker Compose up the project
  become: yes
  community.general.docker_compose:
    project_src: /home/docker-redmine/redmine-prd/
  register: output


