version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.5'
    environment:
      - MARIADB_DATABASE=bitnami_redmine
      - MARIADB_USER=bn_redmine
      - MARIADB_PASSWORD=bn_redmine
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  redmine:
    image: 'manuelchichi/redmine:4.1.1'
    environment:
      - DB_HOST=mariadb
      - DB_NAME=bitnami_redmine
      - DB_USER=bn_redmine
      - DB_PASSWORD=bn_redmine
    volumes:
      - 'redmine_data:/var/www/redmine/files'
  web:
    image: 'manuelchichi/nginx-redmine:1.0.0'
    ports:
      - '80:80'
      
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
