---
# tasks file to initialaze the external database
- name: Copy config template
  become: yes
  template:
    src: config-file.j2
    dest: '/tmp/config-file'

- name: Copy SQL template
  become: yes
  template:
    src: init-database.sql.j2
    dest: '/tmp/init-database.sql'

- name: Create a data container
  become: yes
  community.general.docker_container:
    name: init-database
    image: manuelchichi/redmine-init-database:4.1.1
    volumes:
      - /tmp/config-file:/tmp/config-file
      - /tmp/init-database.sql:/tmp/init-database.sql
    command: mysql -h {{ mariadb_host }} --defaults-extra-file=/tmp/config-file -e 'source /tmp/init-database.sql'
