---
# tasks file to initialaze the external database
- name: Copy config template
  become: yes
  template:
    src: config-file.j2
    dest: '/tmp/config-file'

- name: Copy SQL template
  become: yes
  template:
    src: init-database.sql.j2
    dest: '/tmp/init-database.sql'

- name: Create init-database container
  become: yes
  community.general.docker_container:
    name: init-database
    image: manuelchichi/mysql-client:alpine
    volumes:
      - /tmp/config-file:/tmp/config-file
      - /tmp/init-database.sql:/tmp/init-database.sql
    command: mysql --defaults-extra-file=/tmp/config-file -h {{ mariadb_host }} -e 'source /tmp/init-database.sql'

- name: Remove init-database container
  community.general.docker_container:
    name: init-database
    state: absent

- name: Remove tmp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/config-file
    - /tmp/init-database.sql
